apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
<<<<<<< HEAD
        image: nanajanashia/argocd-app:3.0
=======
        image: nanajanashia/argocd-app:1.0
>>>>>>> 550abae26bf8aade88689742a496fbb67ea9dd96
        ports:
        - containerPort: 8080
